### ISSUE TITLE
stop() throws error throw new Error('Not running'); // error message from dgram_legacy.js

### ISSUE THREAD

**Issue by risro** [ioberry/LoraWAN-Server#3]
When giving the stop() command I get an error:

dgram.js:509
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:509:11)
    at Socket.address (dgram.js:419:8)
    at Socket.<anonymous> (/home/ionsign/gmuSerial/node_modules/lorawan-js/lib/lorawanserver.js:94:90)
    at emitNone (events.js:80:13)
    at Socket.emit (events.js:179:7)
    at socketCloseNT (dgram.js:414:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I think it's because start() has a line (94):
this.socket.on('close', () => { this.status = "STOP"; this.emit("close", this.socket.address() ); });
and when socket emits 'close' this.socket.address() isn't available anymore, if I remove 'this.socket.address()' from the line it doesn't give any errors anymore

I got around it by giving lwServer.socket.removeAllListeners(); before close()

**Comment by suhamera** [comment]
yep, thanx!
